### ISSUE TITLE
nuget package ?

### ISSUE THREAD

**Issue by Nonobis** [angelinn/Xam.Plugin.AutoUpdate#1]
Hello,

Your plugin is excellent, pretty clean ! Good work. :)
Do you have a date for the nuget package? Or is it better to extract the sources for now ?

**Comment by angelinn** [comment]
Hello,

Thank you for the nice words.

I thought I should add some more polishing before publishing it as a nuget package.
Seeing there is some interest, I may squeeze in some time to get it done sooner.
For now you are free to build it from source. 

Also, if you have any suggestions/bug reports, feel free to let me know.

**Comment by Nonobis** [comment]
ok. thanks :)
